"""Closure-V1 one-shot F4 interface-fixed planner-only scope."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
from .current_hasher import hash_json
from .f4_post_stage0_layout_v1 import LAYOUT,SELECTED_EXISTING_CORRIDOR_ID,audit_f4_post_stage0_layout_v1
from .real_sapien_adapter_closure_f4_v2 import IMPLEMENTATION_VERSION
ROOT=Path("/nfs_share/lijunhui");AUDIT=ROOT/"Vault-on-Fvl09/数据构造/实现审计";GROUP="controlled_multi_future_post_stage0_closure_v1";SCOPE="F4_derivation_interface_fixed_planner_only_v2";SEED=20260829;NAMESPACE="closure_v1_f4_derivation_interface_v2_planner_only_seed20260829_run1";AUTH_ID="closure-v1-f4-derivation-interface-v2-run1";OUTPUT=ROOT/"Robotwin2/datasets"/GROUP/NAMESPACE;PARENT=AUDIT/"USER_AUTHORIZATION_POST_STAGE0_CLOSURE_V1_20260831.json";BUDGET=AUDIT/"POST_STAGE0_CLOSURE_V1_F4_BUDGET.json";PUBLICATION=AUDIT/"POST_STAGE0_CLOSURE_V1_F4_SCOPE.json";REVIEW=AUDIT/"F4_POST_STAGE0_LAYOUT_IMPACT_REVIEW_V1.json";OLD_INNER=ROOT/"Robotwin2/datasets/controlled_multi_future_post_stage0_f4_v1/post_stage0_f4_new_layout_planner_only_seed20260829_run1/F4_planner_only/receipt.json";REQUEST=AUDIT/"scope_requests"/GROUP/f"{NAMESPACE}.request.json";SOURCE=AUDIT/"source_locks"/GROUP/f"{NAMESPACE}.source_lock.json";AUTH=AUDIT/"authorizations"/GROUP/f"{NAMESPACE}.authorization.json";GUARD=AUDIT/"gpu_guards"/GROUP/f"{NAMESPACE}.guard.json"
def _sha(v):return hashlib.sha256(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":"),allow_nan=False).encode()).hexdigest()
def budget():
 v={"schema_version":"cmf_closure_v1_f4_budget_v2","implementation_version":IMPLEMENTATION_VERSION,"scope":SCOPE,"family":"F4","planner_query_limit":96,"canonical_prefix_reference_execution_limit":1,"suffix_execution_limit":0,"release_execution_limit":0,"fresh_scene_limit":4,"physics_step_limit":-1,"timeout_seconds":14400,"allowed_physical_gpu_indices":list(range(8)),"automatic_retry":False,"recovery_attempts":0,"maximum_scope_invocations":1,"formal_data":False,"stage0_data":False,"stage0_authorized":False,"stage1_authorized":False};v["budget_receipt_sha256"]=_sha(v);return v
def spec():
 a=audit_f4_post_stage0_layout_v1();
 if a["pass"] is not True:raise ValueError("layout CPU Gate")
 v={"schema_version":"cmf_closure_v1_f4_spec_v2","slot_id":"closure-v1-F4-derivation-interface-v2","scope":SCOPE,"family":"F4","arm":"right","seed":SEED,"generator":"controlled_multi_future_post_stage0_closure_f4_v2_adapter","origin":"post_stage0_closure_v1","scene_layout":json.loads(json.dumps(LAYOUT,sort_keys=True)),"scene_layout_sha256":a["layout_sha256"],"post_stage0_selected_f4_corridor_id":SELECTED_EXISTING_CORRIDOR_ID,"derivation_interface_version":"cmf_f4_derivation_interface_v2","canonical_program_ids":["F4-ABC","F4-ACB","F4-BAC"],"canonical_prefix_reference_execution_count":1,"fresh_program_scene_count":3,"suffix_execution_count":0,"release_execution_count":0,"automatic_retry":False,"recovery_attempts":0,"formal_data":False,"stage0_data":False,"stage0_authorized":False,"stage1_authorized":False,"budget_receipt_sha256":budget()["budget_receipt_sha256"],"stop_condition":"first terminal infrastructure/planner/cleanup result or 3 complete routes"};v["planned_scope_spec_sha256"]=_sha(v);return v
def publication():
 v={"schema_version":"cmf_closure_v1_f4_publication_v2","implementation_version":IMPLEMENTATION_VERSION,"scope":SCOPE,"planned_scope_spec":spec(),"budget":budget(),"layout_review_payload_sha256":"ca9c3c1419a4513c849311eed904246c4784da3b36f306bcee8e9021f133e043","old_failed_inner_receipt_file_sha256":"deef47bee0e58ca1081f355857033898143b84c68f36e7c7a6a51acf65d3a186","stage0_seal_unchanged":True};v["scope_publication_sha256"]=_sha(v);return v
